services:
  - type: web
    name: swasthiq-backend
    env: docker
    repo: https://github.com/sabnoor06/SWASTHIQ_SABNOORFATIMA
    branch: main
    rootDir: backend
    plan: free

  - type: web
    name: swasthiq-frontend
    env: docker
    repo: https://github.com/sabnoor06/SWASTHIQ_SABNOORFATIMA
    branch: main
    rootDir: frontend
    plan: free
